#!/bin/sh

# AX6000 Stable V1.1

# 设置root密码
echo "lkg030418" | passwd root


# 开启SSH
/etc/init.d/dropbear enable


# 开启Web管理
/etc/init.d/uhttpd enable


# 设置Argon主题
uci set luci.main.mediaurlbase='/luci-static/argon'
uci commit luci


exit 0
